spring:
  application:
    name: ito1
  datasource:
    url: jdbc:oracle:thin:@ito_high?TNS_ADMIN=./wallet
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true