spring:
  application:
    name: ito1
  datasource:
    url: jdbc:oracle:thin:@ito_high?TNS_ADMIN=./wallet
    username: ADMIN
    password: ManolitoITO1
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379